
export const MERCHANT_LOGO_DOMAINS: [string, string][] = [
  // ── Monobank-specific (must be before "monomarket") ──────────────────────
  ["mono",                 "monobank.ua"],
  ["приват",               "privatbank.ua"],
  ["privat",               "privatbank.ua"],
  ["ощад",                 "oschadbank.ua"],
  ["розстрочк",            "monobank.ua"],
  ["повне погашення",      "monobank.ua"],
  ["щомісячний платіж",    "monobank.ua"],
  ["monobank",             "monobank.ua"],
  ["монобанк",             "monobank.ua"],

  // ── FinTech & Banking ─────────────────────────────────────────────────────
  ["приватбанк",           "privatbank.ua"],
  ["privatbank",           "privatbank.ua"],
  ["ощадбанк",             "oschadbank.ua"],
  ["oschadbank",           "oschadbank.ua"],
  ["райффайзен",           "raiffeisen.ua"],
  ["raiffeisen",           "raiffeisen.ua"],
  ["пумб",                 "pumb.ua"],
  ["pumb",                 "pumb.ua"],
  ["укрсиббанк",           "ukrsibbank.ua"],
  ["ukrsibbank",           "ukrsibbank.ua"],
  ["сенс банк",            "sensebank.com.ua"],
  ["sense bank",           "sensebank.com.ua"],
  ["а-банк",               "a-bank.com.ua"],
  ["a-bank",               "a-bank.com.ua"],
  ["кредобанк",            "kredobank.ua"],
  ["kredobank",            "kredobank.ua"],
  ["укргазбанк",           "ukrgasbank.ua"],
  ["ukrgasbank",           "ukrgasbank.ua"],
  ["таскомбанк",           "tascombank.ua"],
  ["tascombank",           "tascombank.ua"],
  ["правекс",              "pravex.com.ua"],
  ["правекс банк",         "pravex.com.ua"],
  ["отп банк",             "otpbank.com.ua"],
  ["otp bank",             "otpbank.com.ua"],
  ["izibank",              "izibank.ua"],
  ["ізібанк",              "izibank.ua"],
  ["sportbank",            "sportbank.ua"],
  ["спортбанк",            "sportbank.ua"],
  ["novapay",              "novapay.ua"],
  ["новапей",              "novapay.ua"],
  ["portmone",             "portmone.com"],
  ["easypay",              "easypay.ua"],
  ["іізіпей",              "easypay.ua"],
  ["city24",               "city24.ua"],
  ["liqpay",               "liqpay.com"],
  ["ліквей",               "liqpay.com"],
  ["fondy",                "fondy.eu"],
  ["wayforpay",            "wayforpay.com"],
  ["вейфорпей",            "wayforpay.com"],
  ["ipay.ua",              "ipay.ua"],
  ["monopay",              "monobank.ua"],
  ["вчасно",               "vchasno.ua"],
  ["vchasno",              "vchasno.ua"],
  ["універсал банк",       "universalbank.com.ua"],
  ["revolut",              "revolut.com"],
  ["wise",                 "wise.com"],
  ["paypal",               "paypal.com"],
  ["mastercard",           "mastercard.com"],
  ["visa",                 "visa.com"],

  // ── E-Commerce & Marketplaces ─────────────────────────────────────────────
  ["rozetka",              "rozetka.com.ua"],
  ["розетка",              "rozetka.com.ua"],
  ["prom.ua",              "prom.ua"],
  ["olx",                  "olx.ua"],
  ["shafa",                "shafa.ua"],
  ["kasta",                "kasta.ua"],
  ["каста",                "kasta.ua"],
  ["maudau",               "maudau.ua"],
  ["маудау",               "maudau.ua"],
  ["crafta",               "crafta.ua"],
  ["крафта",               "crafta.ua"],
  ["bigl.ua",              "bigl.ua"],
  ["kabanchik",            "kabanchik.ua"],
  ["кабанчик",             "kabanchik.ua"],
  ["izzi.ua",              "izzi.ua"],
  ["ria.com",              "ria.com"],
  ["auto.ria",             "auto.ria.com"],
  ["dom.ria",              "dom.ria.com"],
  ["work.ua",              "work.ua"],
  ["robota.ua",            "robota.ua"],
  ["amazon",               "amazon.com"],
  ["aliexpress",           "aliexpress.com"],
  ["ebay",                 "ebay.com"],
  ["booking.com",          "booking.com"],
  ["airbnb",               "airbnb.com"],

  // ── Retail & Supermarkets ─────────────────────────────────────────────────
  ["атб",                  "atbmarket.com"],
  ["сільпо",               "silpo.ua"],
  ["silpo",                "silpo.ua"],
  ["епіцентр",             "epicentrk.ua"],
  ["epicentr",             "epicentrk.ua"],
  ["нова лінія",           "nova-liniya.ua"],
  ["nova liniya",          "nova-liniya.ua"],
  ["novus",                "novus.ua"],
  ["новус",                "novus.ua"],
  ["varus",                "varus.ua"],
  ["варус",                "varus.ua"],
  ["фора",                 "fora.ua"],
  ["велика кишеня",        "velyka-kyshenya.ua"],
  ["ашан",                 "auchan.ua"],
  ["auchan",               "auchan.ua"],
  ["metro",                "metro.ua"],
  ["comfy",                "comfy.ua"],
  ["комфі",                "comfy.ua"],
  ["фокстрот",             "foxtrot.ua"],
  ["foxtrot",              "foxtrot.ua"],
  ["алло",                 "allo.ua"],
  ["allo",                 "allo.ua"],
  ["цитрус",               "citrus.ua"],
  ["citrus",               "citrus.ua"],
  ["moyo",                 "moyo.ua"],
  ["мойо",                 "moyo.ua"],
  ["ktc",                  "ktc.ua"],
  ["ева",                  "eva.ua"],
  [" eva ",                "eva.ua"],
  ["watsons",              "watsons.ua"],
  ["ватсонс",              "watsons.ua"],
  ["prostor",              "prostor.ua"],
  ["простор",              "prostor.ua"],
  ["intertop",             "intertop.ua"],
  ["інтертоп",             "intertop.ua"],
  ["jysk",                 "jysk.ua"],
  ["юск",                  "jysk.ua"],
  ["dnipro-m",             "dnipro-m.ua"],
  ["дніпро-м",             "dnipro-m.ua"],
  ["антошка",              "antoshka.ua"],
  ["antoshka",             "antoshka.ua"],
  ["ikea",                 "ikea.com"],
  ["ікеа",                 "ikea.com"],
  ["decathlon",            "decathlon.ua"],
  ["декатлон",             "decathlon.ua"],
  ["sephora",              "sephora.com"],
  ["samsung",              "samsung.com"],
  ["lg electronics",       "lg.com"],
  ["xiaomi",               "xiaomi.com"],
  ["сяомі",                "xiaomi.com"],
  ["asus",                 "asus.com"],
  ["lenovo",               "lenovo.com"],
  ["hp ",                  "hp.com"],
  ["dell",                 "dell.com"],
  ["canon",                "canon.com"],
  ["monomarket",           "mono.market"],

  // ── Logistics & Delivery ──────────────────────────────────────────────────
  ["нова пошта",           "novaposhta.ua"],
  ["nova poshta",          "novaposhta.ua"],
  ["укрпошта",             "ukrposhta.ua"],
  ["ukrposhta",            "ukrposhta.ua"],
  ["meest",                "meest.com"],
  ["міст",                 "meest.com"],
  ["uklon",                "uklon.com.ua"],
  ["укло",                 "uklon.com.ua"],
  ["liki24",               "liki24.com"],
  ["ліки24",               "liki24.com"],
  ["tabletki",             "tabletki.ua"],
  ["таблетки",             "tabletki.ua"],
  ["glovo",                "glovoapp.com"],
  ["глово",                "glovoapp.com"],
  ["bolt food",            "bolt.eu"],
  ["zakaz.ua",             "zakaz.ua"],
  ["busfor",               "busfor.ua"],
  ["бусфор",               "busfor.ua"],
  ["автолюкс",             "autolux.ua"],
  ["autolux",              "autolux.ua"],
  ["uber",                 "uber.com"],
  ["bolt",                 "bolt.eu"],

  // ── Telecom ───────────────────────────────────────────────────────────────
  ["київстар",             "kyivstar.ua"],
  ["kyivstar",             "kyivstar.ua"],
  ["vodafone",             "vodafone.ua"],
  ["водафон",              "vodafone.ua"],
  ["lifecell",             "lifecell.ua"],
  ["лайфселл",             "lifecell.ua"],
  ["volia",                "volia.ua"],
  ["волія",                "volia.ua"],
  ["triolan",              "triolan.net"],
  ["тріолан",              "triolan.net"],
  ["lanet",                "lanet.ua"],
  ["ланет",                "lanet.ua"],
  ["ukrtelecom",           "ukrtelecom.ua"],
  ["укртелеком",           "ukrtelecom.ua"],

  // ── IT & Services ─────────────────────────────────────────────────────────
  ["macpaw",               "macpaw.com"],
  ["ajax",                 "ajax.systems"],
  ["grammarly",            "grammarly.com"],
  ["preply",               "preply.com"],
  ["serpstat",             "serpstat.com"],
  ["depositphotos",        "depositphotos.com"],
  ["laba",                 "laba.pro"],
  ["mate academy",         "mate.academy"],
  ["mate.academy",         "mate.academy"],
  ["hillel",               "ithillel.ua"],
  ["хіллел",               "ithillel.ua"],
  ["skyup",                "skyup.aero"],
  ["windrose",             "windrose.aero"],
  ["reface",               "reface.ai"],
  ["google",               "google.com"],
  ["apple",                "apple.com"],
  ["microsoft",            "microsoft.com"],
  ["zoom",                 "zoom.us"],
  ["openai",               "openai.com"],
  ["chatgpt",              "openai.com"],
  ["canva",                "canva.com"],
  ["adobe",                "adobe.com"],
  ["figma",                "figma.com"],
  ["notion",               "notion.so"],
  ["duolingo",             "duolingo.com"],

  // ── Gas Stations & Energy ─────────────────────────────────────────────────
  ["окко",                 "okko.ua"],
  ["okko",                 "okko.ua"],
  ["wog",                  "wog.ua"],
  ["брсм",                 "brsm.ua"],
  ["brsm",                 "brsm.ua"],
  ["укрнафта",             "ukrnafta.ua"],
  ["klo",                  "klo.ua"],
  ["socar",                "socar.ua"],
  ["сокар",                "socar.ua"],
  ["upg",                  "upg.ua"],
  ["дтек",                 "dtek.ua"],
  ["dtek",                 "dtek.ua"],
  ["нафтогаз",             "naftogaz.com"],
  ["naftogaz",             "naftogaz.com"],
  ["yasno",                "yasno.energy"],
  ["ясно",                 "yasno.energy"],

  // ── Medicine & Pharmacies ─────────────────────────────────────────────────
  ["аптека 911",           "apteka911.ua"],
  ["apteka 911",           "apteka911.ua"],
  ["подорожник",           "podorozhnyk.com.ua"],
  ["podorozhnyk",          "podorozhnyk.com.ua"],
  ["добробут",             "dobrobut.com"],
  ["dobrobut",             "dobrobut.com"],
  ["сінево",               "synevo.ua"],
  ["synevo",               "synevo.ua"],
  ["діла",                 "dila.com.ua"],
  ["dila",                 "dila.com.ua"],
  ["ескулаб",              "eskulab.ua"],
  ["eskulab",              "eskulab.ua"],
  ["медіком",              "medikom.ua"],
  ["medikom",              "medikom.ua"],
  ["оксфорд медікал",      "oxford-med.com.ua"],
  ["oxford medical",       "oxford-med.com.ua"],
  ["оберіг",               "oberig.ua"],
  ["oberig",               "oberig.ua"],
  ["фармак",               "farmak.ua"],
  ["farmak",               "farmak.ua"],
  ["дарниця",              "darnitsa.ua"],
  ["darnitsa",             "darnitsa.ua"],

  // ── Food, Drinks & Restaurants ───────────────────────────────────────────
  ["пузата хата",          "puzatahata.ua"],
  ["puzata hata",          "puzatahata.ua"],
  ["мафія",                "mafia.ua"],
  ["mafia",                "mafia.ua"],
  ["львівські круасани",   "lviv-croissants.com"],
  ["lviv croissants",      "lviv-croissants.com"],
  ["львівська майстерня шоколаду", "chocolate.lviv.ua"],
  ["рошен",                "roshen.com"],
  ["roshen",               "roshen.com"],
  ["немірофф",             "nemiroff.com"],
  ["nemiroff",             "nemiroff.com"],
  ["оболонь",              "obolon.ua"],
  ["obolon",               "obolon.ua"],
  ["шабо",                 "shabo.ua"],
  ["shabo",                "shabo.ua"],
  ["моршинська",           "morshynska.ua"],
  ["чумак",                "chumak.ua"],
  ["chumak",               "chumak.ua"],
  ["торчин",               "torchyn.ua"],
  ["torchyn",              "torchyn.ua"],
  ["сандора",              "sandora.ua"],
  ["sandora",              "sandora.ua"],
  ["starbucks",            "starbucks.com"],
  ["старбакс",             "starbucks.com"],
  ["mcdonald",             "mcdonalds.com"],
  ["макдональд",           "mcdonalds.com"],
  ["kfc",                  "kfc.com"],
  ["domino",               "dominos.com"],
  ["subway",               "subway.com"],
  ["coca-cola",            "coca-cola.com"],
  ["кока-кола",            "coca-cola.com"],
  ["pepsi",                "pepsi.com"],
  ["red bull",             "redbull.com"],
  ["redbull",              "redbull.com"],
  ["heineken",             "heineken.com"],
  ["starbucks",            "starbucks.com"],

  // ── Media & Streaming ─────────────────────────────────────────────────────
  ["megogo",               "megogo.net"],
  ["мегого",               "megogo.net"],
  ["sweet.tv",             "sweet.tv"],
  ["суспільне",            "suspilne.media"],
  ["suspilne",             "suspilne.media"],
  ["1+1",                  "1plus1.ua"],
  ["дія",                  "diia.gov.ua"],
  ["diia",                 "diia.gov.ua"],
  ["укрправда",            "pravda.com.ua"],
  ["liga.net",             "liga.net"],
  ["nv.ua",                "nv.ua"],
  ["netflix",              "netflix.com"],
  ["нетфлікс",             "netflix.com"],
  ["spotify",              "spotify.com"],
  ["спотіфай",             "spotify.com"],
  ["youtube",              "youtube.com"],
  ["ютуб",                 "youtube.com"],
  ["steam",                "steampowered.com"],
  ["playstation",          "playstation.com"],
  ["xbox",                 "xbox.com"],
  ["twitch",               "twitch.tv"],
  ["concert.ua",           "concert.ua"],

  // ── Fashion & Jewelry ─────────────────────────────────────────────────────
  ["kachorovska",          "kachorovska.com"],
  ["качоровська",          "kachorovska.com"],
  ["riot division",        "riotdivision.com"],
  ["sleeper",              "thesleeper.com"],
  ["frolov",               "frolov.ua"],
  ["bevza",                "bevza.com"],
  ["guzema",               "guzema.com"],
  ["укрзолото",            "ukrzoloto.ua"],
  ["ukrzoloto",            "ukrzoloto.ua"],
  ["цум",                  "tsum.ua"],
  ["tsum",                 "tsum.ua"],
  ["zara",                 "zara.com"],
  ["зара",                 "zara.com"],
  ["h&m",                  "hm.com"],
  ["nike",                 "nike.com"],
  ["найк",                 "nike.com"],
  ["adidas",               "adidas.com"],
  ["адідас",               "adidas.com"],
  ["puma",                 "puma.com"],
  ["reebok",               "reebok.com"],
  ["new balance",          "newbalance.com"],
  ["mango",                "mango.com"],
  ["bershka",              "bershka.com"],
  ["stradivarius",         "stradivarius.com"],
  ["massimo dutti",        "massimodutti.com"],
  ["reserved",             "reserved.com"],
  ["sinsay",               "sinsay.com"],
  ["lc waikiki",           "lcwaikiki.com"],
  ["lcwaikiki",            "lcwaikiki.com"],

  // ── Infrastructure & Real Estate ──────────────────────────────────────────
  ["укрзалізниця",         "uz.gov.ua"],
  ["ukrzaliznytsia",       "uz.gov.ua"],
  ["bukovel",              "bukovel.com"],
  ["букoвель",             "bukovel.com"],
  ["atlas weekend",        "atlasweekend.com"],
  ["kernel",               "kernel.ua"],
  ["кернел",               "kernel.ua"],

  // ── Social & Communication ────────────────────────────────────────────────
  ["facebook",             "facebook.com"],
  ["instagram",            "instagram.com"],
  ["telegram",             "telegram.org"],
  ["tiktok",               "tiktok.com"],
  ["тікток",               "tiktok.com"],
  ["viber",                "viber.com"],
  ["вайбер",               "viber.com"],
  ["linkedin",             "linkedin.com"],
  ["skype",                "skype.com"],
  ["whatsapp",             "whatsapp.com"],
];

export function findMerchantLogo(title: string): string | null {
  const lower = title.toLowerCase();
  const found = MERCHANT_LOGO_DOMAINS.find(([key]) => lower.includes(key));
  return found ? `https://unavatar.io/${found[1]}` : null;
}